### ISSUE TITLE
Should this me moved into digicampipe?

### ISSUE THREAD

**Issue by dneise** [calispac/digicamviewer#5]
This package is in my understanding strongly depending on digicampipe.

There is even some code duplication here and in digicampipe, which I think can and should be avoided.
E.g.: [viewer/geometry.py](https://github.com/cta-sst-1m/digicamviewer/blob/master/digicamviewer/geometry.py) is nearly identical to [pipe/utils/geometry.py](https://github.com/cta-sst-1m/digicampipe/blob/master/digicampipe/utils/geometry.py)

Also the viewer cannot be installed when digicampipe is not installed because of this import:
https://github.com/cta-sst-1m/digicamviewer/blob/6ae90bf87947336e9eda2d137283b315ac6bd735/digicamviewer/viewer.py#L3

So the viewer is not an idependent package at all.

**Comment by yrenier** [comment]
That is a very good idea which would make the installation a little bit easier.

**Comment by dneise** [comment]
I think this is done.
